name: Shorebird Android

on:
  push:
    branches:
      - master

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}


jobs:
  shorebird_android:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Check for Secret availability
        id: secret-check
        run: |
          if [ "${{ secrets.SHOREBIRD_TOKEN }}" != '' ]; then
            echo "SHOREBIRD_TOKEN is available"
          else
            echo "SHOREBIRD_TOKEN is not available or is empty"
          fi


      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: â˜• Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: ğŸš€ Use Shorebird
        run: shorebird --version

#      - name: ğŸš€ Shorebird Release
#        if: ${{ github.event.created }}
#        uses: shorebirdtech/shorebird-release@v0
#        with:
#          args: -- artifact apk  -- --no-tree-shake-icons
#          platform: android

      - name: ğŸ©¹ Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        with:
          args:   --allow-asset-diffs -- --no-tree-shake-icons
          platform: android




