name: Shorebird Android

on:
  push:
    branches:
      - master

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}


jobs:
  shorebird_android:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: base64 Token
        run:  echo $'SHOREBIRD_TOKEN' | base64 --decode --ignore-garbage -w 0
      
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1


      - name: ğŸš€ Use Shorebird
        run: shorebird --version

      - name: Check Shorebird
        run: shorebird doctor


#      - name: ğŸš€ Shorebird Release
#        if: ${{ github.event.created }}
#        uses: shorebirdtech/shorebird-release@v0
#        with:
#          args: -- artifact apk  -- --no-tree-shake-icons
#          platform: android

      - name: ğŸš€ Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        with:
          args: -- --no-tree-shake-icons
          platform: android


      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk



